kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: my-nodejs
          image: nodejs-image:latest
          ports:
            - name: https
              containerPort: 4321
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-nodejs-svc
spec:
ports:
  - name: https-4321
    port: 4321
    protocol: TCP
    targetPort: 4321
selector:
  app: server
